### ISSUE TITLE
Initiate Source Code with Next.js

### ISSUE THREAD

**Issue by dilshankarunarathne** [Aztra-Software/institute-management-system#2]
Here are instructions:
1. Create a fork of the **dev** branch of this original repository.
2. Clone the fork to your PC.
3. Create a Next.js Project inside the repository.
4. Commit the changes.
5. Create a pull request with detailed information.
6. Wait for reviews.

**Comment by Lehanranaviraj** [comment]
@dilshankarunarathne 
please check the [PR 3](https://github.com/Aztra-Software/institute-management-system/pull/3 )

**Comment by dilshankarunarathne** [comment]
Great work on your first PR. ❤️
